In [2]:
import numpy as np

In [3]:
test_list = [[1, 2, 5, 8], 
             [2, 3, 6, 9], 
             [3, 4, 7, 10],
             [4, 5, 8, 11]] # 4 x 4 array
test_array = np.array(test_list, int)

### 1. Indexing

In [4]:
print(test_array[1][2]) # 6 출력
print(test_array[1, 2]) # 동일하게 6 출력

6
6


### 2. Slicing

In [5]:
test_array[1:2, :2] # 1번행 이상 / 2번행 미만, 2번 열 미만 출력

array([[2, 3]])

In [6]:
test_array[1, :2] # 동일하게 출력되지만, 위에는 2차원, 이 코드는 1차원으로 출력

array([2, 3])

In [7]:
test_array[:, 1:] # 모든 행, 1번 열 이후 출력

array([[ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10],
       [ 5,  8, 11]])

In [10]:
test_array[0, 0:4:2] # 0행 / 0부터 3열까지 중에 1개씩 건너뛰고 출력

array([1, 5])